apiVersion: v1
kind: LimitRange
metadata:
  name: podlimits
spec:
  limits:
  - max:
      cpu: "700m"
    min:
      cpu: "200m"
    default:
      cpu: "500m"
    defaultRequest:
      cpu: "300m"
    type: Container
