apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    env: prod
    owner: joti
    app: nginxapp
spec: 
  containers:
    - name: container1
      image: nginx
      resources:
        limits:
          cpu: "400m"

---
apiVersion: v1
kind: Service
metadata:
  name: testpodsvc
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
    - port: 8000
      targetPort: 80

