apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modif-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: list-pods
  apiGroup: rbac.authorization.k8s.io
